services:
  postgres:
    image: postgres:15
    # container_name: gymweb-db 
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: gymweb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - isd-network

  backend:
    build:
      context: ./ISD 
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/gymweb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - isd-network      

  frontend:
    build:
      context: ./ISD-frontend 
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - isd-network

volumes:
  pgdata:
  
networks:
  isd-network:
    driver: bridge  